version: '3.9'

services:
  # Spring Boot App
  blog-app:
    container_name: blog-app-java
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      DB_USER: postgres
      DB_PASS: 12345
      DB_HOST: blog-db
      DB_PORT: 5432
      DB_NAME: blog
    ports:
      - "8080:8080"
    depends_on:
      - blog-db
    networks:
      - blog

  # Database
  blog-db:
    container_name: blog-app-db-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blog
    networks:
      - blog

  # Management Database
  blog-pgadmin:
    container_name: blog-app-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - blog-db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'blog@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 12345
    networks:
      - blog

networks:
  # Blog Network
  blog:
    name: blog-network
