server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

database:
  db-engine: postgres
  db-driver: postgresql
  db-driver-class-name: org.postgresql.Driver
  db-host: ${DB_HOST:localhost}
  db-port: ${DB_PORT:5432}
  db-name: ${DB_NAME:blog}
  db-user: ${DB_USER:postgres}
  db-pass: ${DB_PASS:12345}
