server:
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

engine: h2

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      schema-locations: classpath*:db/${engine}/schema.sql
