database:
  db-driver: mysql
  db-driver-class-name: com.mysql.cj.jdbc.Driver
  db-host: ${DATABASE_HOST}
  db-port: ${DATABASE_PORT}
  db-name: ${DATABASE_NAME}
  db-user: ${DATABASE_USER}
  db-pass: ${DATABASE_PASS}
