spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:
    #    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    url: ${DB_URL:jdbc:hsqldb:file:./data/testdb;hsqldb.lock_file=false;DB_CLOSE_ON_EXIT=false;DB_CLOSE_DELAY=-1}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always
