@startuml
left to right direction

skinparam packageStyle rectangle

package "Hotel" {
    usecase "Consult Hotel" as US1
    usecase "Create Hotel" as US2
    usecase "Update Hotel" as US3
    usecase "Delete Hotel" as US4
}

actor :Main Admin: as Admin
actor :Guest: as Client

Client --> (US1)
Client --> (US2)
Client --> (US3)
Client --> (US4)

(US1) <-- Admin
(US2) <-- Admin
(US3) <-- Admin
(US4) <-- Admin
@enduml
