INSERT INTO posts (id, title, content, author)
VALUES (1, 'CELESTE GUTIÉRREZ qui est esse', 'est rerum tempore vitae sequxi sint nihil reprehenderit dolor beatae ea dolores neque fugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis qui aperiam non debitis possimus qui neque nisi nulla', 'sanders'),
       (2, 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'et iusto sed quo iure voluptatem occaecati omnis eligendi aut ad voluptatem doloribus vel accusantium quis pariatur molestiae porro eius odio et labore et velit aut', 'sanders'),
       (3, 'eum et est occaecati', 'ullam et saepe reiciendis voluptatem adipisci sit amet autem assumenda provident rerum culpa quis hic commodi nesciunt rem tenetur doloremque ipsam iure quis sunt voluptatem rerum illo velit', 'sanders'),
       (4, 'nesciunt quas odio', 'repudiandae veniam quaerat sunt sed alias aut fugiat sit autem sed est voluptatem omnis possimus esse voluptatibus quis est aut tenetur dolor neque', 'sanders'),
       (5, 'dolorem eum magni eos aperiam quia', 'ut aspernatur corporis harum nihil quis provident sequi mollitia nobis aliquid molestiae perspiciatis et ea nemo ab reprehenderit accusantium quas voluptate dolores velit et doloremque molestiae', 'sanders'),
       (6, 'magnam facilis autem', 'dolore placeat quibusdam ea quo vitae magni quis enim qui quis quo nemo aut saepe quidem repellat excepturi ut quia sunt ut sequi eos ea sed quas', 'sanders'),
       (7, 'dolorem dolore est ipsam', 'dignissimos aperiam dolorem qui eum facilis quibusdam animi sint suscipit qui sint possimus cum quaerat magni maiores excepturi ipsam ut commodi dolor voluptatum modi aut vitae', 'sanders'),
       (8, 'nesciunt iure omnis dolorem tempora et accusantium', 'consectetur animi nesciunt iure dolore enim quia ad veniam autem ut quam aut nobis et est aut quod aut provident voluptas autem voluptas', 'sanders'),
       (9, 'optio molestias id quia eum', 'quo et expedita modi cum officia vel magni doloribus qui repudiandae vero nisi sit quos veniam quod sed accusamus veritatis error', 'sanders'),
       (10, 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto', 'sanders');
